---
- name: Install Node.js and Apache2
  hosts: localhost

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Node.js and npm
      apt:
        name: npm
        state: present
      become: yes

    - name: Install Express and Socket.IO
      npm:
        name:
          - express
          - socket.io
        global: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present
      become: yes
      
    - name: Configure Apache virtual host
      template:
        src: chat.conf.j2
        dest: /etc/apache2/sites-available/chat.conf
      become: yes
      notify:
        - Enable Apache Virtual Host
        - Enable Apache Modules
        - Restart Apache2

    - name: Enable Apache Virtual Host
      command: a2ensite chat.conf
      become: yes
      notify:
        - Restart Apache2

    - name: Enable Apache Modules
      command: a2enmod proxy proxy_http
      become: yes
      notify:
        - Restart Apache2

    - name: Restart Apache2
      service:
        name: apache2
        state: restarted

